"""
Django settings for amukan project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'apps.core',
    'apps.users',
    'apps.organizations',
    'apps.location',
    'apps.experiences',
    'apps.travel',
    'apps.content',
    'apps.tracking',
    'apps.destinationSearch',
    'apps.recommendation',
    'apps.booking',
    'rest_framework',
    'corsheaders',
]

MB_EMBEDDING_APP_SECRET = os.getenv("MB_EMBEDDING_APP_SECRET")
METABASE_SITE_URL = os.getenv("METABASE_SITE_URL", "http://localhost:3000")
METABASE_EMBEDDING_SECRET = MB_EMBEDDING_APP_SECRET
METABASE_PUBLIC_BASE_URL = METABASE_SITE_URL

HF_API_TOKEN = os.environ.get("HF_API_TOKEN")

# DEBUG desde variable de entorno (default False)
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# ALLOWED_HOSTS desde env: DJANGO_ALLOWED_HOSTS=ip,dominio,otro
_raw_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
if _raw_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(",") if h.strip()]
else:
    # Fallback por si falta la variable de entorno
    ALLOWED_HOSTS = [
        "api.amukan.travel",
        "amukan.travel",
        "www.amukan.travel",
        "127.0.0.1",
        "localhost",
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'amukan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amukan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('POSTGRES_DB', 'amukandb'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'root1234'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'apps.users.auth.UsernameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:3080",
    "http://localhost:3081",
    "https://amukan.travel",
    "https://www.amukan.travel",
    "https://dev.amukan.travel",
    "http://dev.amukan.travel",
    "http://prod.amukan.travel",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # Rate limiting global, es alto para no afectar el uso normal, wasap
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/min',    # invitados: hasta 100 req/min (tu front no se acerca a esto)
        'user': '5000/day',   # usuarios autenticados: hasta 5000 req/día
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}
#Agregado para Metabase

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3080",
    "http://localhost:3081",
    "https://amukan.travel",
    "https://www.amukan.travel",
    "https://dev.amukan.travel",
    "https://api.amukan.travel",
    "https://api-dev.amukan.travel",
    "http://prod.amukan.travel",
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================================
# Configuración de cache recomendada
# ============================================================================

# Para desarrollo local (usando memoria)
"""  # <--- COMENTA ESTE BLOQUE
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'recommendation-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    }
}
"""

# Para producción (usando Redis)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        
        # ¡CORREGIR ESTA LÍNEA!
        # NO USAR: 'redis://127.0.0.1:6379/1'
        'LOCATION': 'redis://redis:6379/1',
        
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PARSER_CLASS': 'redis.connection.HiredisParser',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'reco', # (Prefijo de tu settings.py)
        'TIMEOUT': 86400,     # 24 horas (o lo que necesites)
    }
}

# ======================================================================
# S3 / MinIO configuration
# ======================================================================
# Endpoint interno (para boto3 o SDK dentro de Docker)
S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL", "http://minio:9000")

# Endpoint público (visible desde navegador)
S3_ENDPOINT_PUBLIC = os.getenv("S3_ENDPOINT_PUBLIC", "http://localhost:9000")

# Nombre del bucket (opcional, si lo usas en build_public_url)
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME", "amukan")

#=======================================================================
# Security 
#=======================================================================

if ENVIRONMENT == "production":
    # Cookies solo se enviarán por HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS: indica al navegador que siempre use HTTPS durante 30 días
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 días
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Otras cabeceras de endurecimiento
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"


