services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: ${DEBUG}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
    command: >
      sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_pgvector.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_SITE_URL: ${METABASE_SITE_URL}
      MB_LOCALE: "es"
      MB_DB_FILE: "/metabase-data/metabase.db"
      MB_EMBEDDING_APP_SECRET: ${MB_EMBEDDING_APP_SECRET}
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  metabase_data: