services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: True
      POSTGRES_DB: amukandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: amukandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

