# Dockerfile.postgres
FROM pgvector/pgvector:pg15

# Instalar solo PostGIS (pgvector ya viene incluido)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        postgis \
        postgresql-15-postgis-3 \
        postgresql-15-postgis-3-scripts && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copiar script de inicialización de base de datos directamente al build
COPY init_pgvector.sql /docker-entrypoint-initdb.d/init.sql