# Generated by Django 5.2.4 on 2025-08-03 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTag',
            fields=[
                ('object_tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('object_type', models.CharField(choices=[('EVENT', 'Event'), ('SERVICE', 'Service'), ('PLACE', 'Place'), ('ORGANIZATION', 'Organization'), ('USER', 'User'), ('TRAVELER_TYPE', 'Traveler Type'), ('INTEREST', 'Interest')], max_length=50)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tag')),
            ],
        ),
    ]
