# Generated by Django 5.2.4 on 2025-08-03 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('position', models.CharField(choices=[('COVER', 'Portada'), ('GALLERY', 'Galería'), ('ICON', 'Ícono'), ('BACKGROUND', 'Fondo'), ('MAP_MARKER', 'Marcador de mapa'), ('AVATAR', 'Avatar'), ('DETAIL', 'Detalle')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.UUIDField()),
                ('object_type', models.CharField(choices=[('EVENT', 'Event'), ('SERVICE', 'Service'), ('PLACE', 'Place'), ('ORGANIZATION', 'Organization'), ('USER', 'User'), ('TRAVELER_TYPE', 'Traveler Type'), ('INTEREST', 'Interest')], max_length=50)),
            ],
        ),
    ]
