# Generated by Django 5.2.4 on 2025-10-29 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('bucket', models.CharField(default='amukan', max_length=128)),
                ('storage', models.CharField(default='s3', max_length=32)),
                ('content_type', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, default='', max_length=64)),
                ('checksum_md5', models.CharField(blank=True, default='', max_length=32)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored')], default='pending', max_length=16)),
                ('filename', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_image',
            },
        ),
    ]
