# Generated by Django 5.2.4 on 2025-10-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['organization_id', 'created_at'], name='core_image_organiz_35b7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['status'], name='core_image_status_bca4b1_idx'),
        ),
    ]
