# Generated by Django 5.2.4 on 2025-08-03 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('service_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('place_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.place')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('place_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.place')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.servicetype')),
            ],
        ),
    ]
