# Generated by Django 5.2.4 on 2025-08-23 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('accommodation_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostal'), ('AIRBNB', 'Airbnb'), ('CAMPING', 'Camping'), ('GUESTHOUSE', 'Casa de huéspedes')], max_length=15)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('beds', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('parking', models.BooleanField(default=False)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('place_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('activity_type', models.CharField(choices=[('HIKING', 'Senderismo'), ('MUSEUM', 'Museo'), ('BEACH', 'Playa'), ('SKIING', 'Esquí'), ('SHOPPING', 'Compras'), ('CLIMBING', 'Escalada')], max_length=15)),
                ('duration_minutes', models.IntegerField()),
                ('guide_included', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, null=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('place_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('place_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.place')),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('transport_type', models.CharField(choices=[('BUS', 'Bus'), ('TRAIN', 'Tren'), ('CAR', 'Auto'), ('BIKE', 'Bicicleta'), ('PLANE', 'Avión'), ('BOAT', 'Barco')], max_length=10)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('place_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
