# Generated by Django 5.2.4 on 2025-10-24 00:57

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384)),
                ('accommodation_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostal'), ('AIRBNB', 'Airbnb'), ('CAMPING', 'Camping'), ('GUESTHOUSE', 'Casa de huéspedes'), ('CABIN', 'Cabaña'), ('INN', 'Hostería'), ('APARTMENT', 'Departamento'), ('BED_BREAKFAST', 'Bed & Breakfast'), ('SPA', 'Termas')], max_length=15)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('beds', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('parking', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384)),
                ('activity_type', models.CharField(choices=[('HIKING', 'Senderismo'), ('MUSEUM', 'Museo'), ('BEACH', 'Playa'), ('SKIING', 'Esquí'), ('SHOPPING', 'Compras'), ('CLIMBING', 'Escalada'), ('WALKING TOUR', 'Walking Tour')], max_length=15)),
                ('duration_minutes', models.IntegerField()),
                ('guide_included', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384)),
            ],
        ),
    ]
