# Generated by Django 5.2.4 on 2025-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationservice',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
