# Generated by Django 5.2.4 on 2025-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityservice',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='accommodationservice',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
