# Generated by Django 5.2.4 on 2025-10-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityservice',
            name='activity_type',
            field=models.CharField(choices=[('HIKING', 'Senderismo'), ('MUSEUM', 'Museo'), ('BEACH', 'Playa'), ('SKIING', 'Esquí'), ('SHOPPING', 'Compras'), ('CLIMBING', 'Escalada'), ('WALKING TOUR', 'Walking Tour')], max_length=15),
        ),
    ]
