# Generated by Django 5.2.4 on 2025-09-21 21:38

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_accommodationservice_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
