# Generated by Django 5.2.4 on 2025-08-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_accommodationservice_rating_activityservice_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
