# Generated by Django 5.2.4 on 2025-08-05 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelerType',
            fields=[
                ('traveler_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recommendation_model_version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1)),
                ('nationality', models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('US', 'United States'), ('ES', 'Spain'), ('FR', 'France'), ('DE', 'Germany'), ('JP', 'Japan'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('GB', 'United Kingdom'), ('IT', 'Italy'), ('CN', 'China'), ('IN', 'India'), ('CA', 'Canada'), ('AU', 'Australia')], max_length=2)),
                ('language', models.CharField(choices=[('ES', 'Spanish'), ('EN', 'English'), ('FR', 'French'), ('DE', 'German'), ('JA', 'Japanese'), ('PT', 'Portuguese'), ('ZH', 'Chinese'), ('HI', 'Hindi')], max_length=2)),
                ('currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation_model_version', models.IntegerField(blank=True, null=True)),
                ('traveler_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.travelertype')),
            ],
        ),
        migrations.CreateModel(
            name='UserTravelerTypeHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation_model_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('recommendation_model_version', models.IntegerField()),
                ('traveler_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.travelertype')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.interest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('user_id', 'interest_id')},
            },
        ),
    ]
