# Generated by Django 5.2.4 on 2025-10-18 17:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfavorite',
            name='uq_userfavorite_user_ct_oid',
        ),
        migrations.RemoveIndex(
            model_name='userfavorite',
            name='users_userf_user_id_70afc0_idx',
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='user_fav_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user_id', 'content_type', 'object_id')},
        ),
        migrations.AlterModelTable(
            name='userfavorite',
            table=None,
        ),
    ]
