# Generated by Django 5.2.4 on 2025-08-20 19:01

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('park', 'Park'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('school', 'School'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('museum', 'Museum'), ('supermarket', 'Supermarket'), ('bus_stop', 'Bus Stop'), ('train_station', 'Train Station'), ('beach', 'Beach'), ('viewpoint', 'Viewpoint'), ('climbing_gym', 'Climbing Gym'), ('campground', 'Campground'), ('parking', 'Parking')], max_length=20)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('accessibility_features', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('COUNTRY', 'País'), ('REGION', 'Región'), ('CITY', 'Ciudad'), ('DISTRICT', 'Comuna'), ('NEIGHBORHOOD', 'Barrio')], max_length=20)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
        ),
    ]
