# Generated by Django 5.2.4 on 2025-10-07 22:10

import django.contrib.gis.db.models.fields
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('park', 'Park'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('school', 'School'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('museum', 'Museum'), ('supermarket', 'Supermarket'), ('bus_stop', 'Bus Stop'), ('train_station', 'Train Station'), ('beach', 'Beach'), ('viewpoint', 'Viewpoint'), ('climbing_gym', 'Climbing Gym'), ('campground', 'Campground'), ('parking', 'Parking'), ('bar', 'Bar'), ('pharmacy', 'Pharmacy'), ('bank', 'Bank'), ('atm', 'ATM'), ('library', 'Library'), ('post_office', 'Post Office'), ('police', 'Police Station'), ('fire_station', 'Fire Station'), ('place_of_worship', 'Place of Worship'), ('cinema', 'Cinema'), ('theatre', 'Theatre'), ('stadium', 'Stadium'), ('sports_centre', 'Sports Centre'), ('marketplace', 'Marketplace'), ('shop', 'Shop'), ('mall', 'Mall'), ('embassy', 'Embassy'), ('toilets', 'Public Toilets'), ('fountain', 'Fountain'), ('zoo', 'Zoo'), ('aquarium', 'Aquarium'), ('nightclub', 'Nightclub'), ('fast_food', 'Fast Food'), ('bakery', 'Bakery'), ('dentist', 'Dentist'), ('doctors', 'Doctors'), ('veterinary', 'Veterinary'), ('church', 'Church'), ('model', 'Motel'), ('attraction', 'Attraction'), ('guest_house', 'Guest House'), ('hostel', 'Hostel'), ('artwork', 'Artwork'), ('gallery', 'Gallery'), ('theme_park', 'Theme Park'), ('pub', 'Pub'), ('clinic', 'Clinic'), ('university', 'University'), ('college', 'College'), ('garden', 'Garden'), ('pitch', 'Sports Pitch'), ('swimming_pool', 'Swimming Pool'), ('golf_course', 'Golf Course'), ('fitness_centre', 'Fitness Centre'), ('dance', 'Dance Studio'), ('playground', 'Playground'), ('monument', 'Monument'), ('memorial', 'Memorial'), ('castle', 'Castle'), ('ruins', 'Ruins'), ('archaeological_site', 'Archaeological Site'), ('station', 'Station'), ('stop_position', 'Stop Position'), ('bus_station', 'Bus Station'), ('caravan_site', 'Caravan Site'), ('books', 'Books'), ('stationery', 'Stationery'), ('convenience', 'Convenience'), ('language_school', 'Language School'), ('laundry', 'Laundry'), ('dry_cleaning', 'Dry Cleaning'), ('car_repair', 'Car Repair'), ('hardware_store', 'Hardware Store'), ('concert_hall', 'Concert Hall'), ('botanical_garden', 'Botanical Garden'), ('hot_spring', 'Hot Spring'), ('ski_resort', 'Ski Resort'), ('adventure_park', 'Adventure Park'), ('ice_cream', 'Ice Cream Shop'), ('art_gallery', 'Art Gallery'), ('historic_site', 'Historic Site'), ('shopping_mall', 'Shopping Mall'), ('market', 'Market'), ('unknown', 'Unknown')], max_length=20)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('accessibility_features', models.JSONField(blank=True, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('COUNTRY', 'País'), ('REGION', 'Región'), ('CITY', 'Ciudad'), ('DISTRICT', 'Comuna'), ('NEIGHBORHOOD', 'Barrio')], max_length=20)),
                ('coordinates', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
        ),
    ]
