# Generated by Django 5.2.4 on 2025-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
