# Generated by Django 5.2.4 on 2025-09-15 03:17

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_zone_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('park', 'Park'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('school', 'School'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('museum', 'Museum'), ('supermarket', 'Supermarket'), ('bus_stop', 'Bus Stop'), ('train_station', 'Train Station'), ('beach', 'Beach'), ('viewpoint', 'Viewpoint'), ('climbing_gym', 'Climbing Gym'), ('campground', 'Campground'), ('parking', 'Parking'), ('bar', 'Bar'), ('pharmacy', 'Pharmacy'), ('bank', 'Bank'), ('atm', 'ATM'), ('library', 'Library'), ('post_office', 'Post Office'), ('police', 'Police Station'), ('fire_station', 'Fire Station'), ('place_of_worship', 'Place of Worship'), ('cinema', 'Cinema'), ('theatre', 'Theatre'), ('stadium', 'Stadium'), ('sports_centre', 'Sports Centre'), ('marketplace', 'Marketplace'), ('shop', 'Shop'), ('mall', 'Mall'), ('embassy', 'Embassy'), ('toilets', 'Public Toilets'), ('fountain', 'Fountain'), ('zoo', 'Zoo'), ('aquarium', 'Aquarium'), ('nightclub', 'Nightclub'), ('fast_food', 'Fast Food'), ('bakery', 'Bakery'), ('dentist', 'Dentist'), ('doctors', 'Doctors'), ('veterinary', 'Veterinary'), ('church', 'Church'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
