# Generated by Django 5.2.4 on 2025-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('park', 'Park'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('school', 'School'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('museum', 'Museum'), ('supermarket', 'Supermarket'), ('bus_stop', 'Bus Stop'), ('train_station', 'Train Station'), ('beach', 'Beach'), ('viewpoint', 'Viewpoint'), ('climbing_gym', 'Climbing Gym'), ('campground', 'Campground'), ('parking', 'Parking'), ('bar', 'Bar'), ('pharmacy', 'Pharmacy'), ('bank', 'Bank'), ('atm', 'ATM'), ('library', 'Library'), ('post_office', 'Post Office'), ('police', 'Police Station'), ('fire_station', 'Fire Station'), ('place_of_worship', 'Place of Worship'), ('cinema', 'Cinema'), ('theatre', 'Theatre'), ('stadium', 'Stadium'), ('sports_centre', 'Sports Centre'), ('marketplace', 'Marketplace'), ('shop', 'Shop'), ('mall', 'Mall'), ('embassy', 'Embassy'), ('toilets', 'Public Toilets'), ('fountain', 'Fountain'), ('zoo', 'Zoo'), ('aquarium', 'Aquarium'), ('nightclub', 'Nightclub'), ('fast_food', 'Fast Food'), ('bakery', 'Bakery'), ('dentist', 'Dentist'), ('doctors', 'Doctors'), ('veterinary', 'Veterinary'), ('church', 'Church'), ('model', 'Motel'), ('attraction', 'Attraction'), ('guest_house', 'Guest House'), ('hostel', 'Hostel'), ('artwork', 'Artwork'), ('gallery', 'Gallery'), ('theme_park', 'Theme Park'), ('pub', 'Pub'), ('clinic', 'Clinic'), ('university', 'University'), ('college', 'College'), ('garden', 'Garden'), ('pitch', 'Sports Pitch'), ('swimming_pool', 'Swimming Pool'), ('golf_course', 'Golf Course'), ('fitness_centre', 'Fitness Centre'), ('dance', 'Dance Studio'), ('playground', 'Playground'), ('monument', 'Monument'), ('memorial', 'Memorial'), ('castle', 'Castle'), ('ruins', 'Ruins'), ('archaeological_site', 'Archaeological Site'), ('station', 'Station'), ('stop_position', 'Stop Position'), ('bus_station', 'Bus Station'), ('caravan_site', 'Caravan Site'), ('books', 'Books'), ('stationery', 'Stationery'), ('convenience', 'Convenience'), ('language_school', 'Language School'), ('laundry', 'Laundry'), ('dry_cleaning', 'Dry Cleaning'), ('car_repair', 'Car Repair'), ('hardware_store', 'Hardware Store'), ('concert_hall', 'Concert Hall'), ('botanical_garden', 'Botanical Garden'), ('hot_spring', 'Hot Spring'), ('ski_resort', 'Ski Resort'), ('adventure_park', 'Adventure Park'), ('ice_cream', 'Ice Cream Shop'), ('art_gallery', 'Art Gallery'), ('historic_site', 'Historic Site'), ('shopping_mall', 'Shopping Mall'), ('market', 'Market'), ('resort', 'Resort'), ('bed_and_breakfast', 'Bed & Breakfast'), ('campsite', 'Campsite'), ('taxi_stand', 'Taxi Stand'), ('car_rental', 'Car Rental'), ('clothing_store', 'Clothing Store'), ('convenience_store', 'Convenience Store'), ('department_store', 'Department Store'), ('apartment', 'apartment'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
