# Generated by Django 5.2.4 on 2025-08-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_place_average_price_place_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
