# Generated by Django 5.2.4 on 2025-10-30 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_shared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('scheduled_date', models.DateTimeField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_cost_currency', models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dolar'), ('EUR', 'Euro'), ('GBP', 'Libra'), ('JPY', 'Yen'), ('BRL', 'Real'), ('MXN', 'Peso Mexicano'), ('INR', 'Rupee'), ('CNY', 'Yuan'), ('CAD', 'Dolar Canadiense'), ('AUD', 'Dolar Australiano')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Creador'), ('EDITOR', 'Editor'), ('VIEWER', 'Visualizador')], max_length=20)),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.itinerary')),
            ],
        ),
    ]
