# Generated by Django 5.2.4 on 2025-10-29 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycollaborator',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='itinerary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.itinerary'),
        ),
        migrations.AlterUniqueTogether(
            name='itinerarycollaborator',
            unique_together={('user_id', 'itinerary_id')},
        ),
    ]
