# Generated by Django 5.2.4 on 2025-08-07 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('BOOK', 'Book'), ('SHARE', 'Share'), ('LIKE', 'Like'), ('COMMENT', 'Comment')], max_length=20)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tracking_in_content_702775_idx')],
            },
        ),
    ]
