# Generated by Django 5.2.4 on 2025-10-17 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('BOOK', 'Book'), ('SHARE', 'Share'), ('LIKE', 'Like'), ('COMMENT', 'Comment'), ('SEARCH', 'Search'), ('save_itinerary', 'Guardado de Itinerario')], max_length=20)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
