# Generated by Django 5.2.4 on 2025-08-20 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionStats',
            fields=[
                ('interaction_stats_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('BOOK', 'Book'), ('SHARE', 'Share'), ('LIKE', 'Like'), ('COMMENT', 'Comment'), ('SEARCH', 'Search')], max_length=20)),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('avg_duration_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('top_filter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Interaction Stats',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('BOOK', 'Book'), ('SHARE', 'Share'), ('LIKE', 'Like'), ('COMMENT', 'Comment'), ('SEARCH', 'Search')], max_length=20)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
