# Generated by Django 5.2.4 on 2025-10-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['content_type', 'object_id'], name='tracking_in_content_702775_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['action'], name='tracking_in_action_7a2247_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['interaction_date'], name='tracking_in_interac_5450fd_idx'),
        ),
    ]
