from django.db import models

class Currency(models.TextChoices):
    CLP = 'CLP', 'Peso Chileno'
    USD = 'USD', 'Dolar'
    EUR = 'EUR', 'Euro'
    GBP = 'GBP', 'Libra'
    JPY = 'JPY', 'Yen'
    BRL = 'BRL', 'Real'
    MXN = 'MXN', 'Peso Mexicano'
    INR = 'INR', 'Rupee'
    CNY = 'CNY', 'Yuan'
    CAD = 'CAD', 'Dolar Canadiense'
    AUD = 'AUD', 'Dolar Australiano'

class Language(models.TextChoices):
    ES = 'ES', 'Español'
    EN = 'EN', 'Inglés'
    FR = 'FR', 'Francés'
    DE = 'DE', 'Alemán'
    JA = 'JA', 'Japonés'
    PT = 'PT', 'Portugués'
    ZH = 'ZH', 'Chino'

class Nationality(models.TextChoices):
    CL = 'CL', 'Chile'
    AR = 'AR', 'Argentina'
    US = 'US', 'Estados Unidos'
    ES = 'ES', 'España'
    FR = 'FR', 'Francia'
    DE = 'DE', 'Alemania'
    JP = 'JP', 'Japón'
    BR = 'BR', 'Brazil'
    MX = 'MX', 'México'
    GB = 'GB', 'Reino Unido'
    IT = 'IT', 'Italia'
    CN = 'CN', 'China'
    IN = 'IN', 'India'
    CA = 'CA', 'Canada'
    AU = 'AU', 'Australia'

class Gender(models.TextChoices):
    MALE = 'M', 'Masculino'
    FEMALE = 'F', 'Femenino'
    NON_BINARY = 'N', 'No Binario'
    OTHER = 'O', 'Otro'
    UNSPECIFIED = 'U', 'Prefiero no decir'

class OrganizationUserRole(models.TextChoices):
    ADMIN = 'ADMIN', 'Administrator'
    STAFF = 'STAFF', 'Staff'
    MANAGER = 'MANAGER', 'Manager'
    VIEWER = 'VIEWER', 'Viewer'

class InteractionAction(models.TextChoices):
    VIEW = 'VIEW', 'View'
    CLICK = 'CLICK', 'Click'
    BOOK = 'BOOK', 'Book'
    SHARE = 'SHARE', 'Share'
    LIKE = 'LIKE', 'Like'
    COMMENT = 'COMMENT', 'Comment',
    SEARCH = 'SEARCH', 'Search',
    SAVE_ITINERARY = 'save_itinerary', 'Guardado de Itinerario'

class SubscriptionPlan(models.TextChoices):
    FREE = 'FREE', 'Free'
    BASIC = 'BASIC', 'Basic'
    PRO = 'PRO', 'Pro'
    ENTERPRISE = 'ENTERPRISE', 'Enterprise'

class OrganizationCategory(models.TextChoices):
    EDUCATION = 'EDUCATION', 'Educación'
    HEALTHCARE = 'HEALTHCARE', 'Salud'
    NONPROFIT = 'NONPROFIT', 'ONG'
    GOVERNMENT = 'GOVERNMENT', 'Gobierno'
    TOURISM = 'TOURISM', 'Turismo'
    PRIVATE = 'PRIVATE', 'Privada'
    OTHER = 'OTHER', 'Otro'

class ZoneLevel(models.TextChoices):
    COUNTRY = 'COUNTRY', 'País'
    REGION = 'REGION', 'Región'
    CITY = 'CITY', 'Ciudad'
    DISTRICT = 'DISTRICT', 'Comuna'
    NEIGHBORHOOD = 'NEIGHBORHOOD', 'Barrio'

class PlaceType(models.TextChoices):
    PARK = 'park', 'Park'
    RESTAURANT = 'restaurant', 'Restaurant'
    CAFE = 'cafe', 'Café'
    SCHOOL = 'school', 'School'
    HOSPITAL = 'hospital', 'Hospital'
    HOTEL = 'hotel', 'Hotel'
    MUSEUM = 'museum', 'Museum'
    SUPERMARKET = 'supermarket', 'Supermarket'
    BUS_STOP = 'bus_stop', 'Bus Stop'
    TRAIN_STATION = 'train_station', 'Train Station'
    BEACH = 'beach', 'Beach'
    VIEWPOINT = 'viewpoint', 'Viewpoint'
    CLIMBING_GYM = 'climbing_gym', 'Climbing Gym'
    CAMPGROUND = 'campground', 'Campground'
    PARKING = 'parking', 'Parking'
    BAR = 'bar', 'Bar'
    PHARMACY = 'pharmacy', 'Pharmacy'
    BANK = 'bank', 'Bank'
    ATM = 'atm', 'ATM'
    LIBRARY = 'library', 'Library'
    POST_OFFICE = 'post_office', 'Post Office'
    POLICE = 'police', 'Police Station'
    FIRE_STATION = 'fire_station', 'Fire Station'
    PLACE_OF_WORSHIP = 'place_of_worship', 'Place of Worship'
    CINEMA = 'cinema', 'Cinema'
    THEATRE = 'theatre', 'Theatre'
    STADIUM = 'stadium', 'Stadium'
    SPORTS_CENTRE = 'sports_centre', 'Sports Centre'
    MARKETPLACE = 'marketplace', 'Marketplace'
    SHOP = 'shop', 'Shop'
    MALL = 'mall', 'Mall'
    EMBASSY = 'embassy', 'Embassy'
    TOILETS = 'toilets', 'Public Toilets'
    FOUNTAIN = 'fountain', 'Fountain'
    ZOO = 'zoo', 'Zoo'
    AQUARIUM = 'aquarium', 'Aquarium'
    NIGHTCLUB = 'nightclub', 'Nightclub'
    FAST_FOOD = 'fast_food', 'Fast Food'
    BAKERY = 'bakery', 'Bakery'
    DENTIST = 'dentist', 'Dentist'
    DOCTORS = 'doctors', 'Doctors'
    VETERINARY = 'veterinary', 'Veterinary'
    CHURCH = 'church', 'Church'
    MOTEL = 'model', 'Motel'
    ATTRACTION = 'attraction', 'Attraction'
    GUEST_HOUSE = 'guest_house', 'Guest House'
    HOSTEL = 'hostel', 'Hostel'
    ARTWORK = 'artwork', 'Artwork'
    GALLERY = 'gallery', 'Gallery'
    THEME_PARK = 'theme_park', 'Theme Park'
    PUB = 'pub', 'Pub'
    CLINIC = 'clinic', 'Clinic'
    UNIVERSITY = 'university', 'University'
    COLLEGE = 'college', 'College'
    GARDEN = 'garden', 'Garden'
    PITCH = 'pitch', 'Sports Pitch'
    SWIMMING_POOL = 'swimming_pool', 'Swimming Pool'
    GOLF_COURSE = 'golf_course', 'Golf Course'
    FITNESS_CENTRE = 'fitness_centre', 'Fitness Centre'
    DANCE = 'dance', 'Dance Studio'
    PLAYGROUND = 'playground', 'Playground'
    MONUMENT = 'monument', 'Monument'
    MEMORIAL = 'memorial', 'Memorial'
    CASTLE = 'castle', 'Castle'
    RUINS = 'ruins', 'Ruins'
    ARCHAEOLOGICAL_SITE = 'archaeological_site', 'Archaeological Site'
    STATION = 'station', 'Station'
    STOP_POSITION = 'stop_position', 'Stop Position'
    BUS_STATION = 'bus_station', 'Bus Station'
    CARAVAN_SITE = 'caravan_site', 'Caravan Site'
    BOOKS = 'books', 'Books'
    STATIONERY = 'stationery', 'Stationery'
    CONVENIENCE = 'convenience', 'Convenience'
    LANGUAGE_SCHOOL = 'language_school', 'Language School'
    LAUNDRY = 'laundry', 'Laundry'
    DRY_CLEANING = 'dry_cleaning', 'Dry Cleaning'
    CAR_REPAIR = 'car_repair', 'Car Repair'
    HARDWARE_STORE = 'hardware_store', 'Hardware Store'
    CONCERT_HALL = 'concert_hall', 'Concert Hall'
    BOTANICAL_GARDEN = 'botanical_garden', 'Botanical Garden'
    HOT_SPRING = 'hot_spring', 'Hot Spring'
    SKI_RESORT = 'ski_resort', 'Ski Resort'
    ADVENTURE_PARK = 'adventure_park', 'Adventure Park'
    ICE_CREAM = 'ice_cream', 'Ice Cream Shop'
    ART_GALLERY = 'art_gallery', 'Art Gallery'
    HISTORIC_SITE = 'historic_site', 'Historic Site'
    SHOPPING_MALL = 'shopping_mall', 'Shopping Mall'
    MARKET = 'market', 'Market'
    RESORT = 'resort', 'Resort'
    BED_BREAKFAST = 'bed_and_breakfast', 'Bed & Breakfast'
    CAMPSITE = 'campsite', 'Campsite'
    TAXI_STAND = 'taxi_stand', 'Taxi Stand'
    CAR_RENTAL = 'car_rental', 'Car Rental'
    CLOTHING_STORE = 'clothing_store', 'Clothing Store'
    CONVENIENCE_STORE = 'convenience_store', 'Convenience Store'
    DEPARTMENT_STORE = 'department_store', 'Department Store'
    APARTMENT = 'apartment', 'apartment'
    UNKNOWN = 'unknown', 'Unknown'


class ReservationStatus(models.TextChoices):
    PENDING = 'PENDING', 'Pendiente'
    CONFIRMED = 'CONFIRMED', 'Confirmada'
    CANCELLED = 'CANCELLED', 'Cancelada'
    EXPIRED = 'EXPIRED', 'Expirada'
    COMPLETED = 'COMPLETED', 'Completada'
    REJECTED = 'REJECTED', 'Rechazada'
    REFUNDED = 'REFUNDED', 'Reembolsada'
    WAITLISTED = 'WAITLISTED', 'En lista de espera'
    UNDER_REVIEW = 'UNDER_REVIEW', 'En revisión'

class UserRole(models.TextChoices):
    OWNER = 'OWNER', 'Creador' 
    EDITOR = 'EDITOR', 'Editor'
    VIEWER = 'VIEWER', 'Visualizador'

class ImagePosition(models.TextChoices):
    COVER = 'COVER', 'Portada'
    GALLERY = 'GALLERY', 'Galería'
    ICON = 'ICON', 'Ícono'
    BACKGROUND = 'BACKGROUND', 'Fondo'
    MAP_MARKER = 'MAP_MARKER', 'Marcador de mapa'
    AVATAR = 'AVATAR', 'Avatar'
    DETAIL = 'DETAIL', 'Detalle'

class TransportType(models.TextChoices):
    BUS = 'BUS', 'Bus'
    TRAIN = 'TRAIN', 'Tren'
    CAR = 'CAR', 'Auto'
    BIKE = 'BIKE', 'Bicicleta'
    PLANE = 'PLANE', 'Avión'
    BOAT = 'BOAT', 'Barco'

class AccommodationType(models.TextChoices):
    HOTEL = 'HOTEL', 'Hotel'
    HOSTEL = 'HOSTEL', 'Hostal'
    AIRBNB = 'AIRBNB', 'Airbnb'
    CAMPING = 'CAMPING', 'Camping'
    GUESTHOUSE = 'GUESTHOUSE', 'Casa de huéspedes'
    CABIN = 'CABIN', 'Cabaña'
    INN = 'INN', 'Hostería'
    APARTMENT = 'APARTMENT', 'Departamento'
    BED_BREAKFAST = 'BED_BREAKFAST', 'Bed & Breakfast'
    SPA = 'SPA', 'Termas'

class ActivityType(models.TextChoices):
    HIKING = 'HIKING', 'Senderismo'
    MUSEUM = 'MUSEUM', 'Museo'
    BEACH = 'BEACH', 'Playa'
    SKIING = 'SKIING', 'Esquí'
    SHOPPING = 'SHOPPING', 'Compras'
    CLIMBING = 'CLIMBING', 'Escalada'
    WALKING_TOUR = 'WALKING TOUR', 'Walking Tour'