# Generated by Django 5.2.4 on 2025-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('GOVERNMENT', 'Gobierno'), ('ACCOMMODATION', 'Alojamiento'), ('GASTRONOMY', 'Gastronomía'), ('TOURS_AND_ACTIVITIES', 'Tours y Actividades'), ('EVENT_PRODUCTION', 'Productora de Eventos'), ('TRANSPORT', 'Transporte'), ('RETAIL', 'Comercio'), ('EDUCATION', 'Educación'), ('CULTURE_NONPROFIT', 'Cultura y ONG'), ('HEALTH_WELLNESS', 'Salud y Bienestar'), ('OTHER', 'Otro')], max_length=20),
        ),
    ]
